title: cwk's digital garden
description: where my thoughts and stuffs lives
email: wenkangchen4@gmail.com
url: "https://cwkang1998.github.io"
baseurl: ""
github_username:  cwkang1998

theme: no-style-please
favicon: "favicon.png"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - _pages